# =========================
# Stage 1 : Runtime
# =========================
FROM docker-registry-002.zeuslearning.com/zeuslearning/dotnet/aspnet:10.0-alpine AS base
 
WORKDIR /app
 
EXPOSE 8080
 
# =========================
# Stage 2 : Build
# =========================
FROM docker-registry-002.zeuslearning.com/zeuslearning/dotnet/sdk:10.0-alpine AS build
 
WORKDIR /src
COPY NuGet.Config /root/.nuget/NuGet/NuGet.Config
 
# Copy project file
COPY TrainingDirectory.Api/TrainingDirectory.Api.csproj TrainingDirectory.Api/

# Restore packages
RUN dotnet restore TrainingDirectory.Api/TrainingDirectory.Api.csproj
 
# Copy complete solution
COPY . .
 
# Build
WORKDIR /src/TrainingDirectory.Api
 
RUN dotnet build TrainingDirectory.Api.csproj -c Release -o /app/build
 
# Stage 3 : Publish
FROM build AS publish
 
RUN dotnet publish TrainingDirectory.Api.csproj -c Release -o /app/publish
 

# Stage 4 : Final Runtime
FROM base AS final
 
WORKDIR /app
 
COPY --from=publish /app/publish .
 
ENTRYPOINT ["dotnet","TrainingDirectory.Api.dll"]
 