# Stage 1 : Base Runtime Image
FROM docker-registry-002.zeuslearning.com/zeuslearning/dotnet/aspnet:10.0-alpine AS base
 
WORKDIR /app
 
EXPOSE 8080
 
# Stage 2 : Build Image
FROM docker-registry-002.zeuslearning.com/zeuslearning/dotnet/sdk:10.0-alpine AS build
 
WORKDIR /src
COPY NuGet.Config /root/.nuget/NuGet/NuGet.Config

# Copy only the project file
COPY myapp/myapp.csproj myapp/
 

# Restore NuGet packages
RUN dotnet restore myapp/myapp.csproj 
 
# Copy remaining source code
COPY . .
WORKDIR /src/myapp
 
# Build the project
RUN dotnet build myapp.csproj -c Release -o /app/build
 
# Stage 3 : Publish
FROM build AS publish
 
RUN dotnet publish myapp.csproj -c Release -o /app/publish
 
# Stage 4 : Final Runtime Image
FROM base AS final
 
WORKDIR /app
 
COPY --from=publish /app/publish .
 
ENTRYPOINT ["dotnet","myapp.dll"]